const defaultKeywords = [
  "react", "reactjs", "react.js",
  "node", "nodejs", "node.js",
  "mongodb", "mongo",
  "express", "expressjs", "express.js",
  "rest", "restful", "api",
  "graphql",
  "typescript", "ts",
  "javascript", "js", "es6",
  "python", "django", "flask",
  "git", "github", "gitlab", "bitbucket",
  "docker", "kubernetes", "k8s",
  "aws", "amazon web services", "ec2", "s3",
  "ci/cd", "jenkins", "github actions",
  "agile", "scrum", "kanban",
  "sql", "mysql",
  "postgresql", "postgres",
  "redis",
  "tailwind", "tailwindcss",
  "next.js", "nextjs",
  "vue", "vuejs", "vue.js",
  "angular",
  "html", "html5",
  "css", "css3", "sass", "less",
  "java", "spring", "spring boot",
  "c#", ".net", "dotnet",
  "php", "laravel",
  "ruby", "ruby on rails", "rails",
  "linux", "bash", "shell",
  "azure", "gcp", "google cloud",
  "terraform", "ansible",
  "testing", "jest", "mocha", "cypress",
  "figma", "ui", "ux",
  "machine learning", "ml", "ai", "artificial intelligence",
  "data science", "pandas", "numpy"
];

module.exports = defaultKeywords;
